version: '2'
services:
  redis:
    image: "redis:alpine"
    expose:
     - "6379"
  postgres:
    image: "postgres:12.4"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: wrst
    volumes:
    - ./db:/var/lib/postgresql/data
    expose:
     - "5432"
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/usr/src/app
    links:
      - redis
      - postgres
    depends_on:
      - postgres
      - redis
    environment:
      APP_SETTINGS: "config.DevelopmentConfig"
      DATABASE_URL: "postgresql://wrst:123456@postgres:5432/wrst"
      REDIS_URL: "redis://redis:6379"
      TEST_DATABASE_URL: "postgresql://wrst:123456@postgres:5432/wrst"
      FLASK_ENV: "development"
    command: ["./wait-for-it.sh", "postgres:5432", "--", "python", "-m", "wrst.app"]
